# Generated by Django 6.0 on 2025-12-29 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoAlugavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.IntegerField()),
                ('status', models.CharField(choices=[('DISP', 'Disponivel'), ('ALUG', 'Alugado'), ('MANU', 'Manutenção')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTipo', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_local', models.CharField(max_length=120)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('devolvido', models.BooleanField(default=False)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.equipamentoalugavel')),
            ],
        ),
        migrations.AddField(
            model_name='equipamentoalugavel',
            name='local_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.local'),
        ),
        migrations.CreateModel(
            name='ProdutoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validade', models.DateField()),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.local')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tipoitem')),
            ],
        ),
        migrations.AddField(
            model_name='equipamentoalugavel',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tipoitem'),
        ),
    ]
