# Generated by Django 6.0 on 2026-01-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentoalugavel',
            name='preco',
            field=models.FloatField(default=0.00),
        ),
    ]
