# Generated by Django 6.0 on 2026-01-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_equipamentoalugavel_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentoalugavel',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
