# Generated by Django 6.0 on 2026-01-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_equipamentoalugavel_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(blank=True, max_length=120, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='equipamentoalugavel',
            name='status',
            field=models.CharField(choices=[('DISP', 'Disponivel'), ('ALUG', 'Alugado'), ('MANU', 'Manutenção')], default='DISP', max_length=20),
        ),
    ]
