# Generated by Django 6.0 on 2026-01-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_venda_itemvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='produto_nome_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_nome_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='tipo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.tipoitem'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(blank=True, null=True),
        ),
    ]
