# Generated by Django 6.0 on 2026-01-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_itemvenda_produto_nome_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='local_origem_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='local_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.local'),
        ),
    ]
