# Generated by Django 6.0 on 2026-03-09 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_venda_vendedor_venda_vendedor_nome_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='dataFim',
            field=models.DateField(verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='dataInicio',
            field=models.DateField(verbose_name='Data inicial'),
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_quantidade', models.CharField(choices=[('ENTRADA', 'Entrada/Acrésimo'), ('SAIDA', 'Saída/Baixa'), ('AJUSTE', 'Ajuste Manual')], max_length=20)),
                ('quantidade_alterada', models.IntegerField()),
                ('estoque_anterior', models.PositiveIntegerField()),
                ('estoque_atual', models.PositiveIntegerField()),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(blank=True, max_length=120, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_movimentacao', to='catalog.produtovenda')),
            ],
            options={
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
