# Generated by Django 6.0 on 2026-03-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_locacao_datafim_alter_locacao_datainicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicomovimentacaoestoque',
            old_name='tipo_quantidade',
            new_name='tipo_movimento',
        ),
    ]
