# Generated by Django 6.0 on 2026-03-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_tipo_quantidade_historicomovimentacaoestoque_tipo_movimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimentacaoestoque',
            name='produto_nome_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicomovimentacaoestoque',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_movimentacao', to='catalog.produtovenda'),
        ),
    ]
