# Generated by Django 6.0 on 2026-04-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_historicomovimentacaoestoque_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENCIMENTO', 'Vencimento próximo'), ('ATRASO', 'Aluguel atrasado')], default='VENCIMENTO', max_length=20)),
                ('mensagem', models.TextField()),
                ('lide', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
