# Generated by Django 6.0 on 2026-04-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_notificacaosistema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacaosistema',
            old_name='lide',
            new_name='lida',
        ),
    ]
